allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@iconify-json/simple-icons@1.2.85'
  - '@nuxt/kit@4.4.7'
  - '@nuxt/nitro-server@4.4.7'
  - '@nuxt/schema@4.4.7'
  - '@nuxt/vite-builder@4.4.7'
  - nuxt@4.4.7
  - vue-eslint-parser@10.4.1
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
  - vue-demi
peerDependencyRules:
  ignoreMissing:
    - unhead
  allowedVersions:
    vue-router: '*'
    '@tiptap/y-tiptap': '*'
